# 任务调度配置
task:
  dispatch:
    # 批处理大小
    batch-size: 1000
    # 预加载数量
    preload-count: 20
    # 心跳超时时间（毫秒）
    heartbeat-timeout: 60000
    # 最大重试次数
    max-retry-count: 3
    # 指令队列大小
    command-queue-size: 1000
    # 线程池配置
    thread-pool:
      # 生成池线程池
      producer:
        core-size: 1
        max-size: 1
        queue-capacity: 10
        keep-alive-seconds: 60
      # 发送者线程池
      sender:
        core-size: 1
        max-size: 1
        queue-capacity: 10
        keep-alive-seconds: 60
      # 处理器线程池
      handler:
        core-size: 2
        max-size: 4
        queue-capacity: 100
        keep-alive-seconds: 60
