# 项目相关配置
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 3.8.9
  # 版权年份
  copyrightYear: 2025
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: D:/ruoyi/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math

# 自定义配置
app:
  comm-mode: stdio # 默认是tcp, 可通过启动参数修改为 stdio
  # 数据库文件路径占位符，将在启动时动态设置
  database:
    path: jdbc:sqlite:${app.database.path}
  # 日志目录（供 logback-spring.xml 读取），默认使用用户主目录
  logging:
    path: ${APPDATA:${user.home}}/UVControlSystem/logs

# 后端服务版本配置
backend:
  # 后端服务版本号
  version: v1.0.2
  # 构建时间
  buildTime: 2025-07-27
  # 服务名称
  name: UV-Redio-Server

# TCP服务配置
tcp:
  # TCP服务器端口
  port: 9999
  # 最大连接数
  max-connections: 1000
  # 连接超时时间（毫秒）
  connection-timeout: 30000

# Netty服务器配置
netty:
  # Netty服务器端口（与TCP端口保持一致）
  port: 9999
  # 最大连接数
  max-connections: 1000
  # 连接超时时间（秒）
  connection-timeout: 30
  business-thread-pool-size: 20
  business-queue-capacity: 1000

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

# 日志维护配置（保留天数与清理计划）
maintenance:
  log:
    retention-days: 30
    cron: "0 0 3 * * ?"  # 每天03:00执行

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  # 禁用Web自动配置
  main:
    web-application-type: none
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: false

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.ruoyi.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: sqlite
  supportMethodsArguments: true
  params: count=countSql

# 设备通道连接配置
device:
  connection:
    timeout: 5000        # 连接超时时间(毫秒)
    retry-interval: 30000 # 重连间隔时间(毫秒)
#文件归档配置
business:
  systemLog:
    archive:
      days: 7        # 归档保留天数，默认7
      batchSize: 500  # 每批处理条数，默认500